include(GNUInstallDirs)
include(CMakePackageConfigHelpers)

# Export the actual static dependency graph, with private vendor names/headers
# scoped below Ninlil. No build-directory paths or system crypto substitution.
function(ninlil_package_visit target)
  get_target_property(alias ${target} ALIASED_TARGET)
  if(alias)
    set(target ${alias})
  endif()
  get_property(seen GLOBAL PROPERTY NINLIL_PACKAGE_TARGETS)
  if(target IN_LIST seen)
    return()
  endif()
  set_property(GLOBAL APPEND PROPERTY NINLIL_PACKAGE_TARGETS ${target})
  get_target_property(links ${target} INTERFACE_LINK_LIBRARIES)
  foreach(link IN LISTS links)
    if(link MATCHES "^\\$<BUILD_INTERFACE:")
      continue()
    endif()
    string(REGEX REPLACE "^\\$<LINK_ONLY:(.*)>$" "\\1" link "${link}")
    if(TARGET ${link})
      ninlil_package_visit(${link})
    endif()
  endforeach()
endfunction()

set(package_roots ninlil_posix ninlil_flash_runtime ninlil_security_state ninlil_radio_model)
if(TARGET ninlil_node)
  list(APPEND package_roots ninlil_node ninlil_identity_file ninlil_identity_flash)
endif()
foreach(target IN LISTS package_roots)
  ninlil_package_visit(${target})
endforeach()
get_property(package_targets GLOBAL PROPERTY NINLIL_PACKAGE_TARGETS)
set(declarations "")
set(dependencies "")
foreach(target IN LISTS package_targets)
  string(REGEX REPLACE "^ninlil_" "" name "${target}")
  get_target_property(type ${target} TYPE)
  if(type STREQUAL "INTERFACE_LIBRARY")
    string(APPEND declarations "add_library(Ninlil::${name} INTERFACE IMPORTED)\n")
  elseif(type STREQUAL "STATIC_LIBRARY")
    install(FILES "$<TARGET_FILE:${target}>" DESTINATION ${CMAKE_INSTALL_LIBDIR}/ninlil)
    string(APPEND declarations "add_library(Ninlil::${name} STATIC IMPORTED)\nset_target_properties(Ninlil::${name} PROPERTIES IMPORTED_LOCATION \"\${PACKAGE_PREFIX_DIR}/${CMAKE_INSTALL_LIBDIR}/ninlil/$<TARGET_FILE_NAME:${target}>\")\n")
  else()
    message(FATAL_ERROR "Unsupported Ninlil package dependency ${target}: ${type}")
  endif()
  string(APPEND declarations "set_target_properties(Ninlil::${name} PROPERTIES INTERFACE_INCLUDE_DIRECTORIES \"\${PACKAGE_PREFIX_DIR}/${CMAKE_INSTALL_INCLUDEDIR}/ninlil;\${PACKAGE_PREFIX_DIR}/${CMAKE_INSTALL_INCLUDEDIR}/ninlil/vendor\" INTERFACE_SYSTEM_INCLUDE_DIRECTORIES \"\${PACKAGE_PREFIX_DIR}/${CMAKE_INSTALL_INCLUDEDIR}/ninlil/vendor\")\n")
  foreach(usage COMPILE_DEFINITIONS COMPILE_FEATURES COMPILE_OPTIONS LINK_OPTIONS)
    get_target_property(values ${target} INTERFACE_${usage})
    if(values)
      string(APPEND dependencies "set_property(TARGET Ninlil::${name} PROPERTY INTERFACE_${usage} \"${values}\")\n")
    endif()
  endforeach()
  if(NINLIL_SANITIZE)
    string(APPEND dependencies "target_link_options(Ninlil::${name} INTERFACE -fsanitize=address,undefined)\n")
  endif()
  get_target_property(links ${target} INTERFACE_LINK_LIBRARIES)
  foreach(link IN LISTS links)
    if(link STREQUAL "links-NOTFOUND" OR link MATCHES "^\\$<BUILD_INTERFACE:")
      continue()
    endif()
    string(REGEX REPLACE "^\\$<LINK_ONLY:(.*)>$" "\\1" link "${link}")
    if(TARGET ${link})
      get_target_property(alias ${link} ALIASED_TARGET)
      if(alias)
        set(link ${alias})
      endif()
      string(REGEX REPLACE "^ninlil_" "" link "${link}")
      set(link "Ninlil::${link}")
    endif()
    string(APPEND dependencies "target_link_libraries(Ninlil::${name} INTERFACE ${link})\n")
  endforeach()
endforeach()
file(GENERATE OUTPUT "${CMAKE_CURRENT_BINARY_DIR}/NinlilTargets.cmake"
  CONTENT "if(TARGET Ninlil::posix)\n  return()\nendif()\n${declarations}${dependencies}")
install(DIRECTORY include/ ports/flash/ DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}/ninlil
  FILES_MATCHING PATTERN "*.h")
install(DIRECTORY DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}/ninlil/vendor)
if(TARGET ninlil_node)
  install(DIRECTORY ports/crypto/ ports/posix/ DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}/ninlil
    FILES_MATCHING PATTERN "*.h")
  install(DIRECTORY third_party/libedhoc/include/ "${LIBEDHOC_GENERATED_DIR}/"
    third_party/libedhoc/backends/cbor/include/ third_party/libedhoc/backends/memory/include/
    third_party/libedhoc/backends/log/include/ third_party/libedhoc/helpers/include/
    third_party/libedhoc/externals/zcbor/include/ third_party/libedhoc/externals/mbedtls/include/
    DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}/ninlil/vendor FILES_MATCHING PATTERN "*.h")
  foreach(vendor libedhoc libedhoc/externals/zcbor libedhoc/externals/mbedtls)
    install(FILES "third_party/${vendor}/LICENSE" DESTINATION ${CMAKE_INSTALL_DATADIR}/ninlil/licenses/${vendor})
  endforeach()
  install(DIRECTORY third_party/libedhoc/externals/mbedtls/3rdparty/
    DESTINATION ${CMAKE_INSTALL_DATADIR}/ninlil/licenses/mbedtls-third-party
    FILES_MATCHING PATTERN "*LICENSE*" PATTERN "*COPYING*")
  install(FILES third_party/adapted/PROVENANCE.json
    DESTINATION ${CMAKE_INSTALL_DATADIR}/ninlil/licenses/adaptations)
endif()
configure_package_config_file(cmake/NinlilConfig.cmake.in
  ${CMAKE_CURRENT_BINARY_DIR}/NinlilConfig.cmake
  INSTALL_DESTINATION ${CMAKE_INSTALL_LIBDIR}/cmake/Ninlil)
write_basic_package_version_file(${CMAKE_CURRENT_BINARY_DIR}/NinlilConfigVersion.cmake
  VERSION 0.1.0 COMPATIBILITY SameMinorVersion)
install(FILES ${CMAKE_CURRENT_BINARY_DIR}/NinlilConfig.cmake
  ${CMAKE_CURRENT_BINARY_DIR}/NinlilConfigVersion.cmake ${CMAKE_CURRENT_BINARY_DIR}/NinlilTargets.cmake
  DESTINATION ${CMAKE_INSTALL_LIBDIR}/cmake/Ninlil)
install(FILES LICENSE README.md THIRD_PARTY_NOTICES.md DESTINATION ${CMAKE_INSTALL_DATADIR}/ninlil)
