set(LIBEDHOC_ENABLE_MODULE_TESTS OFF CACHE BOOL "" FORCE)
set(ENABLE_TESTING OFF CACHE BOOL "" FORCE)
set(ENABLE_PROGRAMS OFF CACHE BOOL "" FORCE)
set(CONFIG_LIBEDHOC_LOG_LEVEL 0 CACHE STRING "" FORCE)
set(CONFIG_LIBEDHOC_MEM_BACKEND 2 CACHE STRING "" FORCE)
if(NOT EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/third_party/libedhoc/CMakeLists.txt")
  message(FATAL_ERROR "Run bash scripts/fetch_edhoc.sh before configuring")
endif()
add_subdirectory(third_party/libedhoc EXCLUDE_FROM_ALL)
# Committed, hash-checked upstream compatibility patch; original clone untouched.
get_target_property(zcbor_sources zcbor SOURCES)
list(FILTER zcbor_sources EXCLUDE REGEX "/zcbor_encode\\.c$")
list(APPEND zcbor_sources "${CMAKE_CURRENT_SOURCE_DIR}/third_party/adapted/zcbor_encode.c")
set_property(TARGET zcbor PROPERTY SOURCES "${zcbor_sources}")
get_target_property(cbor_sources backend_cbor SOURCES)
set(cbor_adapted_sources "")
foreach(cbor_source IN LISTS cbor_sources)
  get_filename_component(cbor_name "${cbor_source}" NAME)
  list(APPEND cbor_adapted_sources "${CMAKE_CURRENT_SOURCE_DIR}/third_party/adapted/cbor/${cbor_name}")
endforeach()
set_property(TARGET backend_cbor PROPERTY SOURCES "${cbor_adapted_sources}")
# Dependencies retain their own diagnostics; do not apply first-party warning
# policy to inline implementation in upstream headers.
foreach(vendor mbedcrypto mbedtls mbedx509 libedhoc_api libedhoc_helpers)
  set_property(TARGET ${vendor} PROPERTY INTERFACE_SYSTEM_INCLUDE_DIRECTORIES
    "$<TARGET_PROPERTY:${vendor},INTERFACE_INCLUDE_DIRECTORIES>")
endforeach()
add_library(ninlil_secure STATIC src/ninlil_secure.c src/ninlil_secure_link.c ports/crypto/ninlil_psa.c)
target_include_directories(ninlil_secure PUBLIC include)
target_link_libraries(ninlil_secure PUBLIC ninlil_security_state PRIVATE mbedcrypto)
ninlil_strict_target(ninlil_secure)
add_executable(test_secure tests/test_secure.c)
target_link_libraries(test_secure PRIVATE ninlil_secure mbedcrypto)
ninlil_strict_target(test_secure)
add_test(NAME m2_secure_envelope COMMAND test_secure)
add_library(ninlil_edhoc_helper STATIC
  third_party/adapted/edhoc_cipher_suite_2.c)
target_link_libraries(ninlil_edhoc_helper PUBLIC libedhoc::edhoc
  PRIVATE libedhoc::helpers mbedcrypto)
add_library(ninlil_edhoc STATIC ports/crypto/ninlil_edhoc.c)
target_include_directories(ninlil_edhoc PUBLIC ports/crypto)
target_link_libraries(ninlil_edhoc PUBLIC ninlil_secure libedhoc::edhoc
  PRIVATE ninlil_edhoc_helper libedhoc::helpers mbedcrypto)
ninlil_strict_target(ninlil_edhoc)
add_executable(test_edhoc tests/test_edhoc.c tests/test_support.c)
target_include_directories(test_edhoc PRIVATE tests)
target_include_directories(test_edhoc SYSTEM PRIVATE
  third_party/libedhoc/tests/include third_party/libedhoc/helpers/include)
target_link_libraries(test_edhoc PRIVATE ninlil_edhoc mbedcrypto ninlil_posix)
ninlil_strict_target(test_edhoc)
add_test(NAME m2_edhoc_handshake COMMAND test_edhoc)
add_library(ninlil_control STATIC src/ninlil_join.c src/ninlil_join_wire.c
  src/ninlil_network.c src/ninlil_network_route.c src/ninlil_network_wire.c src/ninlil_relay.c
  src/ninlil_control_fragment.c src/ninlil_airtime.c)
target_include_directories(ninlil_control PUBLIC include)
ninlil_strict_target(ninlil_control)
add_executable(test_join tests/test_join.c)
target_link_libraries(test_join PRIVATE ninlil_control)
ninlil_strict_target(test_join)
add_test(NAME m3_join_lifecycle COMMAND test_join)
add_executable(test_network tests/test_network.c)
target_link_libraries(test_network PRIVATE ninlil_control)
ninlil_strict_target(test_network)
add_test(NAME m4_m5_network_control COMMAND test_network)
add_executable(test_control_fragment tests/test_control_fragment.c)
target_link_libraries(test_control_fragment PRIVATE ninlil_control)
ninlil_strict_target(test_control_fragment)
add_test(NAME m2_control_fragments COMMAND test_control_fragment)
add_library(ninlil_control_log STATIC src/ninlil_control_log.c)
target_include_directories(ninlil_control_log PUBLIC include PRIVATE src)
target_link_libraries(ninlil_control_log PUBLIC ninlil_control)
ninlil_strict_target(ninlil_control_log)
foreach(backend posix flash_runtime)
  add_executable(test_control_log_${backend} tests/test_control_log.c tests/test_support.c)
  target_include_directories(test_control_log_${backend} PRIVATE tests)
  target_link_libraries(test_control_log_${backend} PRIVATE ninlil_control_log ninlil_${backend})
  ninlil_strict_target(test_control_log_${backend})
  add_test(NAME control_log_${backend} COMMAND test_control_log_${backend})
endforeach()
add_executable(test_airtime tests/test_airtime.c)
target_link_libraries(test_airtime PRIVATE ninlil_control)
ninlil_strict_target(test_airtime)
add_test(NAME m5_airtime_scheduler COMMAND test_airtime)

add_library(ninlil_routed STATIC src/ninlil_routed.c)
target_include_directories(ninlil_routed PUBLIC include)
target_link_libraries(ninlil_routed PUBLIC ninlil_secure ninlil_control)
ninlil_strict_target(ninlil_routed)

add_executable(ninlil_secure_network examples/secure_network/main.c
  examples/secure_network/lab_crypto.c examples/secure_network/lab_setup.c
  examples/secure_network/lab_run.c tests/test_support.c)
target_include_directories(ninlil_secure_network PRIVATE tests examples/secure_network)
target_include_directories(ninlil_secure_network SYSTEM PRIVATE third_party/libedhoc/helpers/include)
target_link_libraries(ninlil_secure_network PRIVATE ninlil_routed ninlil_edhoc
  ninlil_control_log ninlil_posix mbedcrypto)
ninlil_strict_target(ninlil_secure_network)
add_test(NAME secure_many_peer_example COMMAND ninlil_secure_network star)
add_test(NAME adaptive_relay_example COMMAND ninlil_secure_network compare)

add_executable(test_network_pump tests/test_network_pump.c ports/esp32s3/ninlil_network_pump.c)
target_include_directories(test_network_pump PRIVATE tests/esp_stub ports/esp32s3)
target_link_libraries(test_network_pump PRIVATE ninlil_routed ninlil_posix)
ninlil_strict_target(test_network_pump)
add_test(NAME esp_network_pump_model COMMAND test_network_pump)
