set(LIBEDHOC_ENABLE_MODULE_TESTS OFF CACHE BOOL "" FORCE)
set(ENABLE_TESTING OFF CACHE BOOL "" FORCE)
set(ENABLE_PROGRAMS OFF CACHE BOOL "" FORCE)
set(CONFIG_LIBEDHOC_LOG_LEVEL 0 CACHE STRING "" FORCE)
set(CONFIG_LIBEDHOC_MEM_BACKEND 2 CACHE STRING "" FORCE)
if(NOT EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/third_party/libedhoc/CMakeLists.txt")
  message(FATAL_ERROR "Run bash scripts/fetch_edhoc.sh before configuring")
endif()
add_subdirectory(third_party/libedhoc EXCLUDE_FROM_ALL)
# Committed, hash-checked upstream compatibility patch; original clone untouched.
get_target_property(zcbor_sources zcbor SOURCES)
list(FILTER zcbor_sources EXCLUDE REGEX "/zcbor_encode\\.c$")
list(APPEND zcbor_sources "${CMAKE_CURRENT_SOURCE_DIR}/third_party/adapted/zcbor_encode.c")
set_property(TARGET zcbor PROPERTY SOURCES "${zcbor_sources}")
get_target_property(cbor_sources backend_cbor SOURCES)
set(cbor_adapted_sources "")
foreach(cbor_source IN LISTS cbor_sources)
  get_filename_component(cbor_name "${cbor_source}" NAME)
  list(APPEND cbor_adapted_sources "${CMAKE_CURRENT_SOURCE_DIR}/third_party/adapted/cbor/${cbor_name}")
endforeach()
set_property(TARGET backend_cbor PROPERTY SOURCES "${cbor_adapted_sources}")
# Dependencies retain their own diagnostics; do not apply first-party warning
# policy to inline implementation in upstream headers.
foreach(vendor mbedcrypto mbedtls mbedx509 libedhoc_api libedhoc_helpers)
  set_property(TARGET ${vendor} PROPERTY INTERFACE_SYSTEM_INCLUDE_DIRECTORIES
    "$<TARGET_PROPERTY:${vendor},INTERFACE_INCLUDE_DIRECTORIES>")
endforeach()
add_library(ninlil_secure STATIC src/ninlil_secure.c src/ninlil_secure_link.c ports/crypto/ninlil_psa.c)
add_library(ninlil_bulk STATIC src/ninlil_bulk.c src/ninlil_bulk_store.c)
target_include_directories(ninlil_bulk PUBLIC include PRIVATE src)
target_link_libraries(ninlil_bulk PRIVATE mbedcrypto)
ninlil_strict_target(ninlil_bulk)
if(NINLIL_BUILD_TESTS)
foreach(backend posix flash_runtime)
  add_executable(test_bulk_${backend} tests/test_bulk.c tests/test_support.c)
  target_include_directories(test_bulk_${backend} PRIVATE tests)
  target_link_libraries(test_bulk_${backend} PRIVATE ninlil_bulk ninlil_${backend} mbedcrypto)
  ninlil_strict_target(test_bulk_${backend})
  add_test(NAME bulk_resume_${backend} COMMAND test_bulk_${backend})
  add_executable(test_bulk_application_${backend} tests/test_bulk_application.c tests/test_support.c embedded/esp32s3/main/node_bulk.c)
  target_include_directories(test_bulk_application_${backend} PRIVATE tests embedded/esp32s3/main src)
  target_compile_definitions(test_bulk_application_${backend} PRIVATE CONFIG_NINLIL_NODE_ID=1)
  target_link_libraries(test_bulk_application_${backend} PRIVATE ninlil_bulk ninlil_node ninlil_${backend} mbedcrypto)
  ninlil_strict_target(test_bulk_application_${backend})
  add_test(NAME bulk_cold_session_${backend} COMMAND test_bulk_application_${backend})
endforeach()
endif()
target_include_directories(ninlil_secure PUBLIC include)
target_link_libraries(ninlil_secure PUBLIC ninlil_security_state PRIVATE mbedcrypto)
ninlil_strict_target(ninlil_secure)
if(NINLIL_BUILD_TESTS)
add_executable(test_secure tests/test_secure.c)
target_link_libraries(test_secure PRIVATE ninlil_secure mbedcrypto)
ninlil_strict_target(test_secure)
add_test(NAME m2_secure_envelope COMMAND test_secure)
endif()
add_library(ninlil_edhoc_helper STATIC
  third_party/adapted/edhoc_cipher_suite_2.c)
target_link_libraries(ninlil_edhoc_helper PUBLIC libedhoc::edhoc
  PRIVATE libedhoc::helpers mbedcrypto)
add_library(ninlil_edhoc STATIC ports/crypto/ninlil_edhoc.c)
target_include_directories(ninlil_edhoc PUBLIC ports/crypto)
target_link_libraries(ninlil_edhoc PUBLIC ninlil_secure libedhoc::edhoc
  PRIVATE ninlil_edhoc_helper libedhoc::helpers mbedcrypto)
ninlil_strict_target(ninlil_edhoc)
if(NINLIL_BUILD_TESTS)
add_executable(test_edhoc tests/test_edhoc.c tests/test_support.c)
target_include_directories(test_edhoc PRIVATE tests)
target_include_directories(test_edhoc SYSTEM PRIVATE
  third_party/libedhoc/tests/include third_party/libedhoc/helpers/include)
target_link_libraries(test_edhoc PRIVATE ninlil_edhoc mbedcrypto ninlil_posix)
ninlil_strict_target(test_edhoc)
add_test(NAME m2_edhoc_handshake COMMAND test_edhoc)
endif()
add_library(ninlil_identity STATIC ports/crypto/ninlil_identity.c)
target_include_directories(ninlil_identity PUBLIC ports/crypto)
target_link_libraries(ninlil_identity PUBLIC ninlil_edhoc mbedcrypto)
ninlil_strict_target(ninlil_identity)
add_library(ninlil_identity_file STATIC ports/posix/ninlil_identity_file.c)
target_include_directories(ninlil_identity_file PUBLIC ports/posix)
target_link_libraries(ninlil_identity_file PUBLIC ninlil_identity)
ninlil_strict_target(ninlil_identity_file)
add_library(ninlil_identity_flash STATIC ports/flash/ninlil_identity_flash.c)
target_include_directories(ninlil_identity_flash PUBLIC ports/flash)
target_link_libraries(ninlil_identity_flash PUBLIC ninlil_identity ninlil_flash_store)
ninlil_strict_target(ninlil_identity_flash)
if(NINLIL_BUILD_TESTS)
add_executable(test_identity tests/test_identity.c tests/test_support.c)
target_include_directories(test_identity PRIVATE tests)
target_link_libraries(test_identity PRIVATE ninlil_identity_file ninlil_identity_flash ninlil_posix)
ninlil_strict_target(test_identity)
add_test(NAME persistent_identity COMMAND test_identity)
endif()
add_library(ninlil_control STATIC src/ninlil_join.c src/ninlil_join_wire.c
  src/ninlil_network.c src/ninlil_network_route.c src/ninlil_network_wire.c src/ninlil_relay.c
  src/ninlil_airtime.c src/ninlil_radio_adapt.c)
target_include_directories(ninlil_control PUBLIC include)
target_link_libraries(ninlil_control PUBLIC ninlil_contract)
ninlil_strict_target(ninlil_control)
if(NINLIL_BUILD_TESTS)
add_executable(test_join tests/test_join.c)
target_link_libraries(test_join PRIVATE ninlil_control)
ninlil_strict_target(test_join)
add_test(NAME m3_join_lifecycle COMMAND test_join)
add_executable(test_network tests/test_network.c)
target_link_libraries(test_network PRIVATE ninlil_control)
ninlil_strict_target(test_network)
add_test(NAME m4_m5_network_control COMMAND test_network)
add_executable(test_network_restart tests/test_network_restart.c)
target_link_libraries(test_network_restart PRIVATE ninlil_control)
ninlil_strict_target(test_network_restart)
add_test(NAME network_restart_fences COMMAND test_network_restart)
add_executable(test_prepare_lease tests/test_prepare_lease.c)
target_link_libraries(test_prepare_lease PRIVATE ninlil_control)
ninlil_strict_target(test_prepare_lease)
add_test(NAME separate_preparation_lease COMMAND test_prepare_lease)
endif()
add_library(ninlil_lease_clock STATIC src/ninlil_lease_clock.c)
target_include_directories(ninlil_lease_clock PUBLIC include)
target_link_libraries(ninlil_lease_clock PUBLIC ninlil_security_state)
ninlil_strict_target(ninlil_lease_clock)
if(NINLIL_BUILD_TESTS)
add_executable(test_lease_clock tests/test_lease_clock.c)
target_include_directories(test_lease_clock PRIVATE tests)
target_link_libraries(test_lease_clock PRIVATE ninlil_lease_clock)
ninlil_strict_target(test_lease_clock)
add_test(NAME lease_clock_restart COMMAND test_lease_clock)
endif()
add_library(ninlil_control_log STATIC src/ninlil_control_log.c src/ninlil_control_collect.c)
target_include_directories(ninlil_control_log PUBLIC include PRIVATE src)
target_link_libraries(ninlil_control_log PUBLIC ninlil_control)
ninlil_strict_target(ninlil_control_log)
if(NINLIL_BUILD_TESTS)
foreach(backend posix flash_runtime)
  add_executable(test_store_binding_${backend} tests/test_store_binding.c tests/test_support.c)
  target_include_directories(test_store_binding_${backend} PRIVATE tests)
  target_link_libraries(test_store_binding_${backend} PRIVATE ninlil_control_log ninlil_${backend})
  ninlil_strict_target(test_store_binding_${backend})
  add_test(NAME store_binding_${backend} COMMAND test_store_binding_${backend})
  add_executable(test_control_log_${backend} tests/test_control_log.c tests/test_support.c)
  target_include_directories(test_control_log_${backend} PRIVATE tests)
  target_link_libraries(test_control_log_${backend} PRIVATE ninlil_control_log ninlil_${backend})
  ninlil_strict_target(test_control_log_${backend})
  add_test(NAME control_log_${backend} COMMAND test_control_log_${backend})
endforeach()
add_executable(test_airtime tests/test_airtime.c)
target_link_libraries(test_airtime PRIVATE ninlil_control)
ninlil_strict_target(test_airtime)
add_test(NAME m5_airtime_scheduler COMMAND test_airtime)
add_executable(test_radio_adapt tests/test_radio_adapt.c)
target_link_libraries(test_radio_adapt PRIVATE ninlil_control)
ninlil_strict_target(test_radio_adapt)
add_test(NAME radio_power_adaptation COMMAND test_radio_adapt)
endif()

add_library(ninlil_routed STATIC src/ninlil_routed.c)
target_include_directories(ninlil_routed PUBLIC include)
target_link_libraries(ninlil_routed PUBLIC ninlil_secure ninlil_control)
ninlil_strict_target(ninlil_routed)

if(NINLIL_BUILD_TESTS)
add_executable(test_network_pump tests/test_network_pump.c tests/test_support.c ports/esp32s3/ninlil_network_pump.c)
target_include_directories(test_network_pump PRIVATE tests tests/esp_stub ports/esp32s3)
target_link_libraries(test_network_pump PRIVATE ninlil_node ninlil_posix mbedcrypto)
ninlil_strict_target(test_network_pump)
add_test(NAME esp_network_pump_model COMMAND test_network_pump)
add_executable(test_sleep_esp tests/test_sleep_esp.c ports/esp32s3/ninlil_sleep_esp.c)
target_include_directories(test_sleep_esp PRIVATE tests/esp_stub ports/esp32s3)
target_link_libraries(test_sleep_esp PRIVATE ninlil_node ninlil_posix)
ninlil_strict_target(test_sleep_esp)
add_test(NAME esp_sleep_model COMMAND test_sleep_esp)
endif()

add_library(ninlil_node STATIC src/ninlil_node_sync.c src/ninlil_node_diagnostics.c src/ninlil_node_forward.c src/ninlil_field_plan.c src/ninlil_node_membership.c src/ninlil_setup.c src/ninlil_admission.c src/ninlil_node_discovery.c src/ninlil_node_enrollment.c src/ninlil_node.c src/ninlil_node_auth.c
  src/ninlil_node_control.c src/ninlil_node_plans.c src/ninlil_node_routes.c
  src/ninlil_node_io.c src/ninlil_node_links.c src/ninlil_node_recovery.c
  src/ninlil_node_lifecycle.c src/ninlil_node_collection.c src/ninlil_node_radio.c)
target_include_directories(ninlil_node PUBLIC include)
target_sources(ninlil_node PRIVATE src/ninlil_node_sleep.c)
target_sources(ninlil_node PRIVATE src/ninlil_root_replacement.c)
target_sources(ninlil_node PRIVATE src/ninlil_deployment_retire.c)
target_link_libraries(ninlil_node PUBLIC ninlil_identity ninlil_lease_clock
  ninlil_routed ninlil_control_log)
ninlil_strict_target(ninlil_node)
if(NINLIL_BUILD_TESTS)
foreach(backend posix flash_runtime)
  add_executable(test_node_${backend} tests/test_node.c tests/test_support.c tests/test_node_bulk.c)
  add_executable(test_node_sleep_${backend} tests/test_node_sleep.c tests/test_support.c tests/test_node_bulk.c)
  target_include_directories(test_node_sleep_${backend} PRIVATE src tests)
  target_link_libraries(test_node_sleep_${backend} PRIVATE ninlil_node ninlil_identity_file ninlil_${backend} ninlil_bulk)
  ninlil_strict_target(test_node_sleep_${backend})
  add_test(NAME node_sleep_${backend} COMMAND test_node_sleep_${backend})
  add_executable(test_deployment_${backend} tests/test_deployment.c tests/test_support.c tests/test_node_bulk.c)
  target_include_directories(test_deployment_${backend} PRIVATE src tests)
  target_link_libraries(test_deployment_${backend} PRIVATE ninlil_node ninlil_identity_file ninlil_${backend} ninlil_bulk)
  target_link_options(test_deployment_${backend} PRIVATE -Wl,--wrap=ninlil_journal_rewrite)
  ninlil_strict_target(test_deployment_${backend})
  add_test(NAME deployment_${backend} COMMAND test_deployment_${backend})
  add_executable(test_root_replacement_${backend} tests/test_root_replacement.c tests/test_support.c tests/test_node_bulk.c)
  target_include_directories(test_root_replacement_${backend} PRIVATE src tests)
  target_link_libraries(test_root_replacement_${backend} PRIVATE ninlil_node ninlil_identity_file ninlil_${backend} ninlil_bulk)
  ninlil_strict_target(test_root_replacement_${backend})
  add_test(NAME root_replacement_${backend} COMMAND test_root_replacement_${backend})
  add_executable(test_field_${backend} tests/test_field_network.c tests/test_support.c tests/test_node_bulk.c)
  target_include_directories(test_field_${backend} PRIVATE src tests)
  target_link_libraries(test_field_${backend} PRIVATE ninlil_node ninlil_identity_file ninlil_${backend} ninlil_bulk)
  ninlil_strict_target(test_field_${backend})
  add_test(NAME field_replacement_${backend} COMMAND test_field_${backend})
  target_include_directories(test_node_${backend} PRIVATE src tests)
  target_link_libraries(test_node_${backend} PRIVATE ninlil_node ninlil_identity_file ninlil_${backend} ninlil_bulk)
  ninlil_strict_target(test_node_${backend})
  add_test(NAME autonomous_node_${backend} COMMAND test_node_${backend})
  add_test(NAME enrollment_${backend} COMMAND test_node_${backend})
  set_tests_properties(enrollment_${backend} PROPERTIES ENVIRONMENT "NINLIL_TEST_ENROLLMENT=1")
  add_test(NAME discovery_${backend} COMMAND test_node_${backend})
  set_tests_properties(discovery_${backend} PROPERTIES ENVIRONMENT "NINLIL_TEST_ENROLLMENT=radio")
  add_test(NAME discovery_slow_${backend} COMMAND test_node_${backend})
  set_tests_properties(discovery_slow_${backend} PROPERTIES ENVIRONMENT "NINLIL_TEST_ENROLLMENT=radio;NINLIL_TEST_SLOW_RADIO=1;NINLIL_TEST_SEED=4")
  add_test(NAME lost_effective_ack_${backend} COMMAND test_node_${backend})
  set_tests_properties(lost_effective_ack_${backend} PROPERTIES ENVIRONMENT "NINLIL_TEST_ENROLLMENT=radio;NINLIL_TEST_SLOW_RADIO=1;NINLIL_TEST_SEED=4;NINLIL_TEST_LOST_EFFECTIVE_ACK=1")
  add_test(NAME autonomous_overheard_${backend} COMMAND test_node_${backend} direct-bootstrap)
  add_test(NAME autonomous_root_relay_${backend} COMMAND test_node_${backend} direct-bootstrap root-relay)
  add_test(NAME autonomous_join_ack_loss_${backend} COMMAND test_node_${backend} direct-bootstrap root-relay lost-join-ack)
  add_test(NAME autonomous_bounded_radio_${backend} COMMAND test_node_${backend} direct-bootstrap root-relay lost-join-ack slow-radio)
  add_test(NAME autonomous_sustained_radio_${backend} COMMAND test_node_${backend} direct-bootstrap root-relay lost-join-ack slow-radio sustained)
  set_tests_properties(autonomous_sustained_radio_${backend} PROPERTIES ENVIRONMENT "NINLIL_TEST_SEED=4")
  add_executable(test_node_application_${backend} tests/test_node_application.c tests/test_support.c
    embedded/esp32s3/main/node_application.c)
  target_include_directories(test_node_application_${backend} PRIVATE src tests embedded/esp32s3/main)
  target_link_libraries(test_node_application_${backend} PRIVATE ninlil_node ninlil_${backend})
  target_link_options(test_node_application_${backend} PRIVATE -Wl,--wrap=ninlil_application_accept)
  ninlil_strict_target(test_node_application_${backend})
  add_test(NAME application_ledger_restart_${backend} COMMAND test_node_application_${backend})
endforeach()
add_executable(test_node_storage tests/test_node_storage.c)
target_include_directories(test_node_storage PRIVATE tests tests/esp_stub src ports/esp32s3)
target_link_libraries(test_node_storage PRIVATE ninlil_node ninlil_identity_flash ninlil_posix)
ninlil_strict_target(test_node_storage)
add_test(NAME node_provisioning_history COMMAND test_node_storage)
add_executable(test_management tests/test_management.c)
target_include_directories(test_management PRIVATE src)
target_link_libraries(test_management PRIVATE ninlil_node ninlil_posix)
ninlil_strict_target(test_management)
add_test(NAME usb_deployment_status COMMAND test_management)
endif()
